/* The landing story's English strings and their approved Arabic, from the
   v15 prototype (Scroll.dc.html, both languages walked side by side) and
   docs/handoff/site-v15/copy/landing.json. Product names, GRINDCTRL, the
   store domain and the password stay in English in both languages. */

export const STORY_AR = {
  "AI try-on": "تجربة افتراضية",
  "Store Chat": "دردشة المتجر",
  "Shopify fashion stores": "متاجر أزياء Shopify",
  "The fitting room your": "غرفة القياس التي",
  "online store was missing.": "افتقدها متجرك الإلكتروني.",
  "Shoppers see your clothes on themselves from one photo and get answers from your store in Arabic or English. We set it up and keep it running.": "يرى المتسوّقون ملابسك عليهم من صورة واحدة، ويحصلون على إجابات من متجرك بالعربية أو الإنجليزية. نحن نجهّز كل شيء ونبقيه يعمل.",
  "Shoppers see your clothes on themselves from one photo and get answers from your store in Arabic or English.": "يرى المتسوّقون ملابسك عليهم من صورة واحدة، ويحصلون على إجابات من متجرك بالعربية أو الإنجليزية.",
  "Try it on yourself": "جرّبها بنفسك",
  "Book a call": "احجز مكالمة",
  "Try it on": "جرّبها عليك",
  "Tap a garment. The same shopper wears it.": "اضغط على قطعة، فيرتديها المتسوّق نفسه.",
  "Compare it with the photo she started from.": "قارنها بالصورة التي بدأت بها.",
  "Switch shoppers. Everyone sees it on themselves.": "بدّل المتسوّق. كلٌّ يراها على نفسه.",
  "Your turn. Pick a shopper and a garment.": "دورك الآن. اختر متسوّقًا وقطعة.",
  "Try-on demo": "عرض التجربة الافتراضية",
  "Pick a shopper, then a garment. The same shopper wears it.": "اختر متسوّقًا ثم قطعة، فيرتديها المتسوّق نفسه.",
  "Pick a garment": "اختر قطعة",
  "Hover the photo to compare": "مرّر فوق الصورة للمقارنة",
  "Try another shopper": "جرّب متسوّقًا آخر",
  "Show the shopper photo this look was made from": "اعرض صورة المتسوّق التي صُنعت منها هذه الإطلالة",
  "Try-on image: sage linen shirt on the first shopper.": "صورة تجربة: قميص الكتان بلون المريمية على المتسوّقة الأولى.",
  "Try-on image: embroidered abaya on the first shopper.": "صورة تجربة: العباية المطرّزة على المتسوّقة الأولى.",
  "Try-on image: denim overshirt on the second shopper.": "صورة تجربة: قميص الجينز الخارجي على المتسوّق الثاني.",
  "Try-on image: knit polo on the second shopper.": "صورة تجربة: قميص البولو المحبوك على المتسوّق الثاني.",
  "Try-on image: sage linen shirt on the third shopper.": "صورة تجربة: قميص الكتان بلون المريمية على المتسوّقة الثالثة.",
  "Try-on image: satin midi skirt on the third shopper.": "صورة تجربة: تنورة الساتان على المتسوّقة الثالثة.",
  "Try-on image: denim shirt on the fourth shopper.": "صورة تجربة: قميص الجينز على المتسوّق الرابع.",
  "Try-on image: knit polo on the fourth shopper.": "صورة تجربة: قميص البولو المحبوك على المتسوّق الرابع.",
  "Try-on image: floral tiered dress on the fifth shopper.": "صورة تجربة: الفستان المزهر على المتسوّقة الخامسة.",
  "Try-on image: straight jeans on the fifth shopper.": "صورة تجربة: الجينز المستقيم على المتسوّقة الخامسة.",
  "Try-on image: denim shirt on the sixth shopper.": "صورة تجربة: قميص الجينز على المتسوّق السادس.",
  "Try-on image: crew sweatshirt on the sixth shopper.": "صورة تجربة: السويتشيرت على المتسوّق السادس.",
  "AI render": "صورة بالذكاء الاصطناعي",
  "Her photo": "صورتها",
  "His photo": "صورته",
  "Hover to compare": "مرّر للمقارنة",
  "Pick a shopper": "اختر متسوّقًا",
  "Show the first shopper": "اعرض المتسوّقة الأولى",
  "Show the second shopper": "اعرض المتسوّق الثاني",
  "Show the third shopper": "اعرض المتسوّقة الثالثة",
  "Show the fourth shopper": "اعرض المتسوّق الرابع",
  "Show the fifth shopper": "اعرض المتسوّقة الخامسة",
  "Show the sixth shopper": "اعرض المتسوّق السادس",
  "Sage linen shirt": "قميص كتان بلون المريمية",
  "Embroidered abaya": "عباية مطرّزة",
  "Denim overshirt": "قميص جينز خارجي",
  "Knit polo": "قميص بولو محبوك",
  "Satin midi skirt": "تنورة ساتان متوسطة الطول",
  "Denim shirt": "قميص جينز",
  "Floral tiered dress": "فستان مزهر بطبقات",
  "Straight jeans": "جينز بقصّة مستقيمة",
  "Crew sweatshirt": "سويتشيرت بياقة دائرية",
  "Try-on images on AI-generated models.": "صور التجربة على عارضين مولَّدين بالذكاء الاصطناعي.",
  "Store Chat demo": "عرض دردشة المتجر",
  "G": "G",
  "GrindCTRL demo store": "متجر GrindCTRL التجريبي",
  "Chat language": "لغة الدردشة",
  "EN": "EN",
  "Scroll": "مرّر",
  "How the try-on demo plays as you scroll: Tap a garment. The same shopper wears it. Compare it with the photo she started from. Switch shoppers. Everyone sees it on themselves. Your turn. Pick a shopper and a garment.": "كيف يعمل عرض التجربة أثناء التمرير: اضغط على قطعة فيرتديها المتسوّق نفسه. قارنها بالصورة التي بدأت بها. بدّل المتسوّق، فكلٌّ يراها على نفسه. دورك الآن: اختر متسوّقًا وقطعة.",
  "Live store": "المتجر المباشر",
  "A real store. Try it there.": "متجر حقيقي. جرّبها هناك.",
  "Shopify store": "متجر Shopify",
  "Try-on on every product": "تجربة على كل منتج",
  "Open the live store": "افتح المتجر المباشر",
  "Real store and products at grindctrl.myshopify.com. The chat lines are demo text.": "متجر ومنتجات حقيقية على grindctrl.myshopify.com. رسائل الدردشة نص تجريبي.",
  "AI operations": "عمليات الذكاء الاصطناعي",
  "Your team and the AI": "فريقك والذكاء الاصطناعي",
  "run support together.": "يديران الدعم معًا.",
  "Every conversation is answered, checked or handed to the right person, and you can see all of it.": "كل محادثة يُرد عليها أو تُراجع أو تُحوَّل إلى الشخص المناسب، وترى ذلك كله.",
  "What the AI does": "ما يفعله الذكاء الاصطناعي",
  "Answers from what you teach it": "يجيب مما تعلّمه له",
  "Sizing, delivery and care, from your store knowledge, in Arabic or English.": "المقاسات والتوصيل والعناية، من معرفة متجرك، بالعربية أو الإنجليزية.",
  "Order status inside the chat": "حالة الطلب داخل الدردشة",
  "Read-only, once the email matches the order. No refunds or edits.": "للقراءة فقط، بعد تطابق البريد مع الطلب. لا استرداد ولا تعديل.",
  "Photos read, hard cases handed off": "قراءة الصور وتحويل الحالات الصعبة",
  "The AI describes the photo and hands off with the reason. Your team gets an email.": "يصف الذكاء الاصطناعي الصورة ويحوّل المحادثة مع السبب. ويصل بريد إلى فريقك.",
  "Your team takes over": "فريقك يتولّى الأمر",
  "Assign it, add a private note, reply with a saved answer. The AI steps back.": "عيّنها، وأضف ملاحظة خاصة، ورُد بإجابة محفوظة. ويتنحّى الذكاء الاصطناعي.",
  "Animated demo of support run by the AI and your team: questions answered from store knowledge, order status looked up read-only, a photo described and handed to the team with the reason, and a teammate taking over with a private note and a saved reply.": "عرض متحرك لدعم يديره الذكاء الاصطناعي وفريقك: إجابات من معرفة المتجر، واستعلام عن حالة الطلب للقراءة فقط، وصورة تُوصف وتُحوَّل إلى الفريق مع السبب، وزميل يتولّى الأمر بملاحظة خاصة ورد محفوظ.",
  "AI agent": "وكيل الذكاء الاصطناعي",
  "Store knowledge": "معرفة المتجر",
  "Shopify orders": "طلبات Shopify",
  "Photo reader": "قارئ الصور",
  "Answer in chat": "رد في الدردشة",
  "Hand off": "تحويل",
  "Closed by AI": "أغلقها الذكاء الاصطناعي",
  "Team inbox": "صندوق وارد الفريق",
  "Today in your dashboard": "اليوم في لوحة التحكم",
  "Demo data": "بيانات تجريبية",
  "Conversations": "المحادثات",
  "Handed to your team": "حُوّلت إلى فريقك",
  "Waiting now": "بانتظار الرد الآن",
  "Demo data. Order status needs read access to your store's orders. Setup, tuning and ongoing care are part of the service.": "بيانات تجريبية. تتطلب حالة الطلب صلاحية قراءة طلبات متجرك. الإعداد والضبط والمتابعة المستمرة جزء من الخدمة.",
  "Demo data. Order status needs read access to your store's orders.": "بيانات تجريبية. تتطلب حالة الطلب صلاحية قراءة طلبات متجرك.",
  "n8n": "n8n",
  "HubSpot": "HubSpot",
  "Custom steps, built during setup": "خطوات مخصصة تُبنى أثناء الإعداد",
  "The product": "المنتج",
  "One system, five connected parts": "نظام واحد، خمسة أجزاء مترابطة",
  "Watch each part work, shown with demo data. Where a part is not finished, it says so.": "شاهد كل جزء وهو يعمل، ببيانات تجريبية. وحين لا يكون الجزء مكتملًا نقول ذلك.",
  "Parts of the system": "أجزاء النظام",
  "Storefront": "واجهة المتجر",
  "Live": "مباشر",
  "AI try-on on your product pages.": "تجربة افتراضية على صفحات منتجاتك.",
  "Conversation": "المحادثة",
  "Store Chat answers from your store knowledge and hands off when needed.": "تجيب دردشة المتجر من معرفة متجرك وتحوّل المحادثة عند الحاجة.",
  "Customer": "العميل",
  "Name, email and the full thread stay together in your inbox. CRM sync is planned.": "الاسم والبريد والمحادثة كاملة معًا في صندوق الوارد. المزامنة مع نظام إدارة العملاء قيد التخطيط.",
  "Workflow": "سير العمل",
  "The AI answers or hands off with the reason, your team gets an email, and every case lands in the dashboard.": "يجيب الذكاء الاصطناعي أو يحوّل مع السبب، ويصل بريد إلى فريقك، وتظهر كل حالة في لوحة التحكم.",
  "Report": "التقرير",
  "Store Chat and try-on activity in your dashboard. Revenue attribution is planned.": "نشاط دردشة المتجر والتجربة في لوحة التحكم. نسب الإيرادات قيد التخطيط.",
  "Animated demo: on a product page a shopper taps Try it on with AI, adds her photo, generates a try-on preview of the shirt on herself and adds it to her cart.": "عرض متحرك: في صفحة منتج تضغط متسوّقة على جرّبها بالذكاء الاصطناعي، وتضيف صورتها، وتنشئ معاينة للقميص عليها، ثم تضيفه إلى سلتها.",
  "GRINDCTRL DEMO STORE": "متجر GRINDCTRL التجريبي",
  "Size": "المقاس",
  "S": "S",
  "M": "M",
  "L": "L",
  "XL": "XL",
  "Add to cart": "أضِف إلى السلة",
  "Try it on with AI": "جرّبها بالذكاء الاصطناعي",
  "Upload your photo": "ارفع صورتك",
  "Your photo is ready": "صورتك جاهزة",
  "Creating your preview": "جارٍ إنشاء معاينتك",
  "Try-On Preview": "معاينة التجربة",
  "Drag and drop your photo here": "اسحب صورتك وأفلتها هنا",
  "or click to browse · JPG, PNG, WebP": "أو اضغط للتصفح · JPG، PNG، WebP",
  "Mapping product to your photo…": "مطابقة المنتج مع صورتك…",
  "Rendering try-on preview…": "إنشاء معاينة التجربة…",
  "Your photo is used only to create this try-on preview.": "تُستخدم صورتك فقط لإنشاء هذه المعاينة.",
  "The preview is visual guidance, not an exact sizing guarantee.": "المعاينة إرشاد بصري وليست ضمانًا دقيقًا للمقاس.",
  "Generate Try-On Preview": "إنشاء معاينة التجربة",
  "Adding…": "جارٍ الإضافة…",
  "What the shopper sees on your product page · Demo data": "ما يراه المتسوّق في صفحة منتجك · بيانات تجريبية",
  "Animated demo: a shopper asks about sizing and the assistant answers from the store knowledge. She rates the answer, asks about stock, leaves her email for the reply, and the team joins with an answer.": "عرض متحرك: متسوّقة تسأل عن المقاس فيجيب المساعد من معرفة المتجر. تقيّم الإجابة، وتسأل عن التوفر، وتترك بريدها للرد، ثم ينضم الفريق بإجابة.",
  "Assistant may reply automatically": "قد يرد المساعد تلقائيًا",
  "Does the sage linen shirt run true to size? I'm between M and L.": "هل مقاس قميص الكتان بلون المريمية مضبوط؟ أنا بين M و L.",
  "Assistant": "المساعد",
  "It's cut oversized, so M already sits relaxed and L gives a longer, looser fit. Want a teammate to confirm stock in sage?": "قصّته واسعة، فمقاس M مريح أصلًا، ومقاس L أطول وأوسع. هل تريد أن يتأكد أحد من الفريق من توفر اللون؟",
  "Thanks for your feedback!": "شكرًا على رأيك!",
  "Yes please, is M in stock in sage?": "نعم من فضلك، هل مقاس M متوفر بلون المريمية؟",
  "Team": "الفريق",
  "Good news: M in sage is in stock. You can order it now.": "خبر سار: مقاس M متوفر بلون المريمية. يمكنك الطلب الآن.",
  "Connecting you with our team…": "جارٍ توصيلك بفريقنا…",
  "Our team joined the conversation": "انضم فريقنا إلى المحادثة",
  "Where should we reply?": "أين نرد عليك؟",
  "you@example.com": "you@example.com",
  "salma@example.com": "salma@example.com",
  "Not now": "ليس الآن",
  "Send": "إرسال",
  "Thanks — we will reply to you there.": "شكرًا، سنرد عليك هناك.",
  "Ask anything…": "اسأل أي شيء…",
  "Powered by GRINDCTRL": "بدعم من GRINDCTRL",
  "What the shopper sees in Store Chat · Demo data": "ما يراه المتسوّق في دردشة المتجر · بيانات تجريبية",
  "Animated demo: a new conversation from Salma arrives in the team inbox and opens with the whole thread, what the AI said and why it was handed off.": "عرض متحرك: تصل محادثة جديدة من سلمى إلى صندوق وارد الفريق وتُفتح بكامل تفاصيلها، وما قاله الذكاء الاصطناعي، وسبب تحويلها.",
  "Search conversations": "ابحث في المحادثات",
  "All": "الكل",
  "Assigned to me": "المعيّنة لي",
  "Salma": "سلمى",
  "now": "الآن",
  "Needs a reply": "تحتاج إلى رد",
  "AI handed this off": "حوّلها الذكاء الاصطناعي",
  "A": "A",
  "Anonymous shopper": "متسوّق مجهول",
  "4h ago": "قبل 4 ساعات",
  "Do you ship to Alexandria, and how long does it take?": "هل تشحنون إلى الإسكندرية، وكم يستغرق التوصيل؟",
  "AI handling": "يتولّاها الذكاء الاصطناعي",
  "N": "N",
  "noura@example.com": "noura@example.com",
  "1d ago": "قبل يوم",
  "Can I exchange it for a smaller size?": "هل يمكنني استبدالها بمقاس أصغر؟",
  "Resolved": "تم الحل",
  "CRM sync is planned.": "المزامنة مع نظام إدارة العملاء قيد التخطيط.",
  "Take over": "تولَّ المحادثة",
  "Mark resolved": "تعليم كمحلولة",
  "↪ AI handed this conversation to your team": "↪ حوّل الذكاء الاصطناعي هذه المحادثة إلى فريقك",
  "You are replying": "أنت من يرد الآن",
  "Return to AI": "أعِدها إلى الذكاء الاصطناعي",
  "Assign to…": "عيّن إلى…",
  "Omar": "عمر",
  "AI": "الذكاء الاصطناعي",
  "What your team sees in the inbox · Demo data": "ما يراه فريقك في صندوق الوارد · بيانات تجريبية",
  "How work moves between the AI and your team. Pick a case: a sizing question the AI answers, a stock question it hands to your team with an email alert, or a photo the AI reads and labels for your team. Each case ends in the dashboard.": "كيف ينتقل العمل بين الذكاء الاصطناعي وفريقك. اختر حالة: سؤال عن المقاس يجيب عنه الذكاء الاصطناعي، أو سؤال عن التوفر يحوّله إلى فريقك مع تنبيه بالبريد، أو صورة يقرؤها ويصنّفها لفريقك. وتنتهي كل حالة في لوحة التحكم.",
  "How work moves": "كيف ينتقل العمل",
  "Pick a case to follow it": "اختر حالة لتتابعها",
  "Pick a case": "اختر حالة",
  "Sizing question": "سؤال عن المقاس",
  "Stock question": "سؤال عن التوفر",
  "Photo of an order": "صورة لطلب",
  "Shopper writes": "المتسوّق يكتب",
  "AI reads it": "يقرؤها الذكاء الاصطناعي",
  "AI answers": "يجيب الذكاء الاصطناعي",
  "Hands off": "يحوّل",
  "Email alert": "تنبيه بالبريد",
  "Dashboard": "لوحة التحكم",
  "How work moves between the AI and your team · Demo data": "كيف ينتقل العمل بين الذكاء الاصطناعي وفريقك · بيانات تجريبية",
  "Animated demo: the dashboard counts Store Chat conversations, AI-closed chats, handoffs, reply time and satisfaction, and try-on generations per day.": "عرض متحرك: تحصي لوحة التحكم محادثات دردشة المتجر، والمحادثات التي أغلقها الذكاء الاصطناعي، والتحويلات، ووقت الرد، والرضا، وعمليات إنشاء التجربة يوميًا.",
  "Revenue attribution is planned.": "نسب الإيرادات قيد التخطيط.",
  "Store Chat is live": "دردشة المتجر تعمل الآن",
  "Conversations · 7 days": "المحادثات · 7 أيام",
  "Needed your team": "احتاجت إلى فريقك",
  "Open right now": "مفتوحة الآن",
  "Median first reply (7d)": "متوسط أول رد (7 أيام)",
  "Satisfaction · 30 days": "الرضا · 30 يومًا",
  "Try-on": "التجربة",
  "avg render 11.4s": "متوسط الإنشاء 11.4 ث",
  "Generations, 7 days": "عمليات الإنشاء، 7 أيام",
  "up 25% on last week": "ارتفاع 25% عن الأسبوع الماضي",
  "Success rate, 7 days": "نسبة النجاح، 7 أيام",
  "3 failed": "3 لم تكتمل",
  "Generations per day": "عمليات الإنشاء يوميًا",
  "Sep 16 · 12 generations": "16 سبتمبر · 12 عملية إنشاء",
  "Sep 11": "11 سبتمبر",
  "Sep 17": "17 سبتمبر",
  "What you see in the dashboard · Demo data": "ما تراه في لوحة التحكم · بيانات تجريبية",
  "Animated walkthroughs recreated from the product's own screens, with demo data.": "جولات متحركة أُعيد بناؤها من شاشات المنتج نفسه، ببيانات تجريبية.",
  "Real results": "نتائج حقيقية",
  "Same shopper, every garment": "المتسوّق نفسه، في كل قطعة",
  "Each shopper, then the same shopper in another garment. Tap a look to switch it.": "كل متسوّق، ثم المتسوّق نفسه في قطعة أخرى. اضغط على إطلالة لتبدّلها.",
  "Try-on results": "نتائج التجربة",
  "Show the same shopper in embroidered abaya": "اعرض المتسوّقة نفسها بالعباية المطرّزة",
  "Try-on image: sage linen shirt.": "صورة تجربة: قميص الكتان بلون المريمية.",
  "Womenswear": "ملابس نسائية",
  "Try it with your photo": "جرّبها بصورتك",
  "Show the same shopper in knit polo": "اعرض المتسوّق نفسه بقميص البولو المحبوك",
  "Try-on image: denim overshirt.": "صورة تجربة: قميص الجينز الخارجي.",
  "Menswear": "ملابس رجالية",
  "Show the same shopper in satin midi skirt": "اعرض المتسوّقة نفسها بتنورة الساتان",
  "Try-on image: denim shirt.": "صورة تجربة: قميص الجينز.",
  "Show the same shopper in straight jeans": "اعرض المتسوّقة نفسها بالجينز المستقيم",
  "Try-on image: floral tiered dress.": "صورة تجربة: الفستان المزهر.",
  "Girls": "بنات",
  "Show the same shopper in crew sweatshirt": "اعرض المتسوّق نفسه بالسويتشيرت",
  "Boys": "أولاد",
  "Show another shopper in the same skirt": "اعرض متسوّقة أخرى بالتنورة نفسها",
  "Try-on image: satin midi skirt.": "صورة تجربة: تنورة الساتان.",
  "Same skirt, two shoppers": "التنورة نفسها، على متسوّقتين",
  "Show the same shopper in sage linen shirt": "اعرض المتسوّقة نفسها بقميص الكتان",
  "Shopper photo.": "صورة المتسوّق.",
  "Photo, then try-on": "الصورة، ثم التجربة",
  "Works inside your stack": "يعمل داخل أدواتك",
  "Plugs into the store you already run.": "يتصل بالمتجر الذي تديره بالفعل.",
  "How GrindCTRL connects: your Shopify store (native app and theme blocks) sends products and read-only order status to GrindCTRL, where try-on, Store Chat, the team inbox and the dashboard are live. GrindCTRL hands conversations to your team with the reason and email alerts. n8n and HubSpot connect through custom setup.": "كيف يتصل GrindCTRL: يرسل متجرك على Shopify (تطبيق أصلي ومكوّنات القالب) المنتجات وحالة الطلبات للقراءة فقط إلى GrindCTRL، حيث تعمل التجربة ودردشة المتجر وصندوق وارد الفريق ولوحة التحكم. ويحوّل GrindCTRL المحادثات إلى فريقك مع السبب وتنبيهات بالبريد. ويتصل n8n وHubSpot عبر إعداد مخصص.",
  "Your Shopify store": "متجرك على Shopify",
  "Native app": "تطبيق أصلي",
  "Theme blocks": "مكوّنات القالب",
  "Products": "المنتجات",
  "Orders, read-only": "الطلبات، للقراءة فقط",
  "Handoffs": "التحويلات",
  "Email alerts": "تنبيهات بالبريد",
  "Your team": "فريقك",
  "Handoff with the reason": "تحويل مع السبب",
  "Assigned to Omar": "عُيّنت لعمر",
  "Private note added": "أُضيفت ملاحظة خاصة",
  "Custom setup": "إعداد مخصص",
  "How it works": "كيف يعمل",
  "From try-on to your team": "من التجربة إلى فريقك",
  "Follow one shopper through GrindCTRL. Real product screens, shown with demo data.": "تابع متسوّقة واحدة عبر GrindCTRL. شاشات المنتج الحقيقية، ببيانات تجريبية.",
  "Salma tries the linen shirt on": "سلمى تجرّب قميص الكتان",
  "One photo, any product page with the try-on block.": "صورة واحدة، على أي صفحة منتج فيها مكوّن التجربة.",
  "Does the sage linen shirt run true to size?": "هل مقاس قميص الكتان بلون المريمية مضبوط؟",
  "It's cut oversized, so M already sits relaxed and L gives a longer, looser fit.": "قصّته واسعة، فمقاس M مريح أصلًا، ومقاس L أطول وأوسع.",
  "She asks about size. The assistant answers.": "تسأل عن المقاس، فيجيب المساعد.",
  "Replies are grounded in the knowledge you add.": "الردود مبنية على المعرفة التي تضيفها.",
  "3h ago": "قبل 3 ساعات",
  "Handed to Omar with a private note": "حُوّلت إلى عمر مع ملاحظة خاصة",
  "Handoffs, assignment, private notes and saved replies for your team.": "تحويلات وتعيين وملاحظات خاصة وردود محفوظة لفريقك.",
  "See it working": "شاهده وهو يعمل",
  "Give shoppers a reason to feel sure before checkout.": "امنح المتسوّقين سببًا للثقة قبل الدفع.",
  "Book a call and we will map try-on and Store Chat to your Shopify theme, catalog and customer questions.": "احجز مكالمة وسنربط التجربة ودردشة المتجر بقالب Shopify الخاص بك وكتالوجك وأسئلة عملائك.",
  "Open the live demo store": "افتح المتجر التجريبي المباشر",
  "Shopify": "Shopify",
  "The fitting room your online store was missing.": "غرفة القياس التي افتقدها متجرك الإلكتروني.",
  "Tap to compare": "اضغط للمقارنة",
  "Real store and products. The chat lines are demo text.": "متجر ومنتجات حقيقية. رسائل الدردشة نص تجريبي.",
  "Your team and the AI run support together.": "فريقك والذكاء الاصطناعي يديران الدعم معًا.",
  "Demo data. Setup and ongoing care are part of the service.": "بيانات تجريبية. الإعداد والمتابعة المستمرة جزء من الخدمة.",
  "Demo data.": "بيانات تجريبية.",
  "← Back to conversations": "← العودة إلى المحادثات",
  "Sizing": "المقاس",
  "Stock": "التوفر",
  "Photo": "الصورة",
  "Each shopper, then the same shopper in another garment.": "كل متسوّق، ثم المتسوّق نفسه في قطعة أخرى.",
  "Ask the store": "اسأل المتجر",
  "Answers from your store in Arabic or English, and a person from your team when it matters.": "إجابات من متجرك بالعربية أو الإنجليزية، وشخص من فريقك حين يلزم.",
  "Book a call and we will map try-on and Store Chat to your Shopify theme and catalog.": "احجز مكالمة وسنربط التجربة ودردشة المتجر بقالب Shopify الخاص بك وكتالوجك.",
  "Results": "النتائج",
  "Close menu": "إغلاق القائمة",
  "Open menu": "فتح القائمة",
  "Page scenes": "مشاهد الصفحة",
  "Go to Try it on": "انتقل إلى جرّبها عليك",
  "Go to Live store": "انتقل إلى المتجر المباشر",
  "Go to AI operations": "انتقل إلى عمليات الذكاء الاصطناعي",
  "Go to The product": "انتقل إلى المنتج",
  "Go to Results": "انتقل إلى النتائج",
  "photo received": "تم استلام الصورة",
  "garment mapped": "تمت مطابقة القطعة",
  "look rendered": "اكتملت الإطلالة",
  "added to cart": "أُضيفت إلى السلة",
  "store opened": "فُتح المتجر",
  "product viewed": "عُرض المنتج",
  "try-on opened": "فُتحت التجربة",
  "chat answered": "تم الرد في الدردشة",
  "message in": "رسالة جديدة",
  "intent: sizing": "النية: المقاس",
  "knowledge lookup": "بحث في المعرفة",
  "handoff to team": "تحويل إلى الفريق",
  "knowledge saved": "حُفظت المعرفة",
  "reply saved": "حُفظ الرد",
  "handoff rule on": "قاعدة التحويل مفعّلة",
  "report ready": "التقرير جاهز",
  "look 1 rendered": "الإطلالة 1 جاهزة",
  "same shopper": "المتسوّق نفسه",
  "look 2 rendered": "الإطلالة 2 جاهزة",
  "shared": "تمت المشاركة",
  "tried on": "جرّب القطعة",
  "asked a question": "طرح سؤالًا",
  "person joined": "انضم شخص من الفريق",
  "call booked": "حُجزت مكالمة",
  "Your turn: press it on the live store": "دورك: اضغطه في المتجر المباشر",
  "Open this page on the live store": "افتح هذه الصفحة في المتجر المباشر",
  "Open this page on the live demo store, in a new tab": "افتح هذه الصفحة في المتجر التجريبي المباشر، في علامة تبويب جديدة",
  "Reads and decides": "يقرأ ويقرّر",
  "What you teach it": "ما تعلّمه له",
  "Read-only lookup": "استعلام للقراءة فقط",
  "Describes the photo": "يصف الصورة",
  "In the same chat": "في الدردشة نفسها",
  "With the reason": "مع السبب",
  "No team needed": "دون حاجة للفريق",
  "Assign, note, reply": "تعيين، ملاحظة، رد",
  "Is there a size guide?": "هل يوجد دليل مقاسات؟",
  "Size guide found": "وُجد دليل المقاسات",
  "Link sent in chat": "أُرسل الرابط في الدردشة",
  "Rated helpful": "قُيّم بأنه مفيد",
  "Where is order #1042?": "أين الطلب رقم 1042؟",
  "Asks for the email": "يطلب البريد الإلكتروني",
  "Email matched": "تطابق البريد",
  "Shipped, tracking sent": "شُحن، وأُرسل رقم التتبع",
  "Sent a photo": "أرسل صورة",
  "Reads the photo": "يقرأ الصورة",
  "Torn seam, damaged": "درزة ممزقة، القطعة تالفة",
  "Reason: damaged item": "السبب: قطعة تالفة",
  "Email sent to team": "أُرسل بريد إلى الفريق",
  "Saved reply ready": "الرد المحفوظ جاهز",
  "Omar replied in chat": "ردّ عمر في الدردشة",
  "Steps back for Omar": "يتنحّى لصالح عمر",
  "Name, email and the full thread stay together in your inbox.": "الاسم والبريد والمحادثة كاملة معًا في صندوق الوارد.",
  "The AI answers or hands off, your team gets an email, and every case lands in the dashboard.": "يجيب الذكاء الاصطناعي أو يحوّل، ويصل بريد إلى فريقك، وتظهر كل حالة في لوحة التحكم.",
  "Store Chat and try-on activity in your dashboard.": "نشاط دردشة المتجر والتجربة في لوحة التحكم.",
  "Checks store knowledge": "يراجع معرفة المتجر",
  "Size guide sent": "أُرسل دليل المقاسات",
  "A shopper asks: Is there a size guide?": "متسوّق يسأل: هل يوجد دليل مقاسات؟",
  "The AI checks what you taught it about sizing.": "يراجع الذكاء الاصطناعي ما علّمته له عن المقاسات.",
  "It answers with your size guide.": "ويجيب بدليل مقاساتك.",
  "The shopper rates the answer helpful.": "يقيّم المتسوّق الإجابة بأنها مفيدة.",
  "The dashboard counts it as closed by AI.": "تحتسبها لوحة التحكم مغلقة بالذكاء الاصطناعي.",
  "Handled start to finish by the AI.": "تولّاها الذكاء الاصطناعي من البداية إلى النهاية.",
  "Is M in stock in sage?": "هل مقاس M متوفر بلون المريمية؟",
  "Needs a teammate": "تحتاج إلى زميل",
  "Reason: confirm stock": "السبب: تأكيد التوفر",
  "A shopper needs you": "متسوّق يحتاج إليك",
  "Omar · note · reply": "عمر · ملاحظة · رد",
  "A shopper asks: Is M in stock in sage?": "متسوّق يسأل: هل مقاس M متوفر بلون المريمية؟",
  "The AI decides a teammate should confirm stock.": "يقرّر الذكاء الاصطناعي أن يتأكد زميل من التوفر.",
  "It hands the chat to your team with the reason.": "ويحوّل المحادثة إلى فريقك مع السبب.",
  "Your team gets an email: A shopper needs you.": "يصل بريد إلى فريقك: متسوّق يحتاج إليك.",
  "Omar picks it up, leaves a private note and replies.": "يتولاها عمر، ويترك ملاحظة خاصة، ثم يرد.",
  "The dashboard counts it under Needed your team.": "تحتسبها لوحة التحكم ضمن ما احتاج إلى فريقك.",
  "The shopper got a person. Your team got the context.": "حصل المتسوّق على شخص، وحصل فريقك على السياق.",
  "Photo: a torn seam": "الصورة: درزة ممزقة",
  "Label: Looks damaged": "التصنيف: تبدو تالفة",
  "Omar takes over": "عمر يتولّى الأمر",
  "A shopper sends a photo of her order.": "متسوّقة ترسل صورة لطلبها.",
  "The AI reads the photo and notes what it shows.": "يقرأ الذكاء الاصطناعي الصورة ويدوّن ما تظهره.",
  "Your team sees it with a label: Looks damaged.": "يراها فريقك مع تصنيف: تبدو تالفة.",
  "Omar takes over the chat.": "يتولّى عمر المحادثة.",
  "The AI labels it. A person decides.": "الذكاء الاصطناعي يصنّف، والإنسان يقرّر.",
  "Text and photos": "نصوص وصور",
  "From store knowledge": "من معرفة المتجر",
  "To your team": "إلى فريقك",
  "Assign · note · reply": "تعيين · ملاحظة · رد",
  "What happened": "ما الذي حدث",
  "Copy": "نسخ",
  "Copied": "تم النسخ",
  "Selected, press Ctrl+C": "تم التحديد، اضغط Ctrl+C",
  "Store password copied": "تم نسخ كلمة مرور المتجر",
  "Copy the store password": "انسخ كلمة مرور المتجر",
} as const;

export type StoryText = keyof typeof STORY_AR;

/** Background trace lines per scene, in English; the story translates them with the table above. */
export const STORY_TRACES = {
  A: ["photo received", "garment mapped", "look rendered", "added to cart"],
  S: ["store opened", "product viewed", "try-on opened", "chat answered"],
  O: ["message in", "intent: sizing", "knowledge lookup", "handoff to team"],
  B: ["knowledge saved", "reply saved", "handoff rule on", "report ready"],
  C: ["look 1 rendered", "same shopper", "look 2 rendered", "shared"],
  R: ["tried on", "asked a question", "person joined", "call booked"],
} as const;
