/* Generates the homepage try-on proof set through the production pipeline.

   Runs lib/try-on/image-runner.ts unchanged: same prompt, same provider call,
   same validation. The only local shim is that garment files are served for
   one fixed cdn.shopify.com URL, so they pass the runner's own Shopify-CDN
   guard instead of the runner being edited to accept local files.

   Usage (from apps/web-next, loads provider credentials without printing them):
     node --env-file=.env.local node_modules/vite-node/vite-node.mjs \
       --config vitest.config.ts scripts/generate-tryon-proof.ts -- <inputDir>

   Inputs are AI-generated model and garment images supplied by the owner, and
   the manifest records that, so the site can label them honestly. */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import { runImageGeneration } from '@/lib/try-on/image-runner';

const PAIRS = [
  { id: 'woman-linen-shirt', shopper: 'shopper-woman.png', garment: 'garment-linen-shirt.png', name: 'sage linen shirt' },
  { id: 'woman-abaya', shopper: 'shopper-woman.png', garment: 'garment-abaya.png', name: 'black embroidered abaya' },
  { id: 'man-denim-overshirt', shopper: 'shopper-man.png', garment: 'garment-denim-overshirt.png', name: 'denim overshirt' },
  { id: 'man-knit-polo', shopper: 'shopper-man.png', garment: 'garment-knit-polo.png', name: 'navy knit polo' },
] as const;

const CDN_PREFIX = 'https://cdn.shopify.com/grindctrl-demo/';
const OUT_DIR = path.join(process.cwd(), 'public', 'landing', 'proof', 'tryon');

async function toWebp(input: Buffer, file: string, width: number) {
  await sharp(input).resize({ width, withoutEnlargement: true }).webp({ quality: 84, effort: 5 }).toFile(file);
}

async function main() {
  const inputDir = process.argv.at(-1);
  if (!inputDir || !process.env.OPENROUTER_API_KEY) {
    throw new Error('Pass the input directory and load OPENROUTER_API_KEY via --env-file.');
  }
  const model = process.env.TRYON_MODEL;
  if (!model) throw new Error('TRYON_MODEL is not set.');

  const realFetch = globalThis.fetch;
  globalThis.fetch = (async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = typeof input === 'string' ? input : input instanceof URL ? input.href : input.url;
    if (url.startsWith(CDN_PREFIX)) {
      const bytes = await readFile(path.join(inputDir, url.slice(CDN_PREFIX.length)));
      return new Response(bytes, { headers: { 'content-type': 'image/png' } });
    }
    return realFetch(input, init);
  }) as typeof fetch;

  await mkdir(path.join(OUT_DIR, 'inputs'), { recursive: true });
  const manifest: Record<string, unknown>[] = [];

  for (const pair of PAIRS) {
    const photo = await readFile(path.join(inputDir, pair.shopper));
    const job = await runImageGeneration(
      `proof-${pair.id}`,
      'premium-ringer-tee',
      `data:image/png;base64,${photo.toString('base64')}`,
      null,
      model,
      `${CDN_PREFIX}${pair.garment}`,
      pair.name,
    );
    if (job.status !== 'completed' || !job.resultImageUrl) {
      console.log(`${pair.id}: FAILED (${job.message ?? 'no message'})`);
      manifest.push({ id: pair.id, status: job.status });
      continue;
    }
    const b64 = job.resultImageUrl.slice(job.resultImageUrl.indexOf(',') + 1);
    await toWebp(Buffer.from(b64, 'base64'), path.join(OUT_DIR, `${pair.id}.webp`), 1024);
    manifest.push({
      id: pair.id,
      status: job.status,
      shopperInput: pair.shopper,
      garmentInput: pair.garment,
      provider: job.meta.provider,
      costEstimate: job.meta.costEstimate,
      generatedAt: job.completedAt,
    });
    console.log(`${pair.id}: completed, cost ${job.meta.costEstimate ?? 'unknown'}`);
  }

  for (const file of new Set(PAIRS.flatMap((p) => [p.shopper, p.garment]))) {
    await toWebp(await readFile(path.join(inputDir, file)), path.join(OUT_DIR, 'inputs', file.replace(/\.png$/, '.webp')), 768);
  }

  await writeFile(
    path.join(OUT_DIR, 'manifest.json'),
    `${JSON.stringify({ note: 'Results generated by lib/try-on/image-runner.ts. Shopper and garment inputs are AI-generated images supplied by the owner.', pairs: manifest }, null, 2)}\n`,
  );
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
