# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fc095fe656d9029fdc249a4af2315f19"
application_url = "https://shopify.grindctrl.cloud"
embedded = true
name = "grindctrl-tryon"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_app_proxy"

[app_proxy]
url = "https://grindctrl.cloud/api/shopify/proxy"
prefix = "apps"
subpath = "grindctrl"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://shopify.grindctrl.cloud/auth/callback",
  "https://shopify.grindctrl.cloud/auth/shopify/callback",
  "https://shopify.grindctrl.cloud/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = false
